# Generated by Django 3.0.8 on 2020-08-07 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20200807_1100'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200803_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('service_rate', models.CharField(choices=[(1, 'Happy'), (0, 'Good'), (-1, 'Sad')], default=0, max_length=1)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Minimun rate is 1'), django.core.validators.MaxValueValidator(5, message='Maximum rate is 5')])),
                ('review', models.TextField(max_length=300)),
                ('realty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realty_feedbacks', to='realty.Realty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
