# Generated by Django 3.0.8 on 2020-08-05 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('c', 'Cash'), ('r', 'Credit Card')], default='c', max_length=1)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='reservation.Reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
