# Generated by Django 3.0.8 on 2020-08-03 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='realty',
            options={'verbose_name': 'Realty'},
        ),
    ]
