# Generated by Django 3.0.8 on 2020-08-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20200803_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='realty',
            options={'verbose_name_plural': 'Realty'},
        ),
    ]
