# Generated by Django 3.1 on 2020-08-09 12:05

from django.db import migrations, models
import django.db.models.deletion
import realty.models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_auto_20200807_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=realty.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='realty.category'),
        ),
    ]
