# Generated by Django 3.1 on 2020-09-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20200809_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
