# Generated by Django 3.1 on 2020-09-01 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_room_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='realty', to='realty.category'),
            preserve_default=False,
        ),
    ]
